# Generated by Django 3.0.7 on 2021-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200805_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
