# Generated by Django 3.0.7 on 2021-02-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_info_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
